### PR TITLE
Noise Filter

### PR DESCRIPTION
**Pull request by samuelsoe**
Hi:

A very nice library. I added noise filter to the project. Please check it out.

### CODE REVIEW

**Comment by ghrom** [comment]
Any chance you could add de-noise, please? ;)

**Comment by esilverberg** [comment]
That one looks trickier. If you're interested in adding it, adapt the code from ImageMagick found here:

http://www.google.com/codesearch#I0cABDTB4TA/pub/FreeBSD/ports/distfiles/ImageMagick-6.3.2-0.tar.bz2%7Cqy9T8VaIuJE/ImageMagick-6.3.2/magick/effect.c&q=reducenoise&type=cs&exact_package=ftp://ftp.freebsd.org/pub/FreeBSD/ports/distfiles/ImageMagick-6.3.2-0.tar.bz2

Search for "Image *ReduceNoiseImage" and you'll find the method that performs this filter.

**Comment by ghrom** [comment]
Thank you, I'll look into it.

**Comment by sureshjagnani** [comment]
HI

Application is Crash in iOS 6.. Please help to sort out ..Thanks in Advance.

**Pull request merged**
